server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

tuya.base-url=https://openapi-sg.iotbing.com
tuya.device-id=a31eb1ded013b84ec7d1op
tuya.access-id=${TUYA_ACCESS_ID:}
tuya.access-secret=${TUYA_ACCESS_SECRET:}
